- hosts: Fedora
  become: true
  become_user: root
  tasks:
    - name: Upgrade all packages through dnf
      ansible.builtin.dnf:
        name: "*"
        state: latest

- hosts: OMV
  become: true
  become_user: root
  tasks:
    - name: Update apt repo and cache on all Debian/Ubuntu boxes
      ansible.builtin.apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

    - name: Upgrade all packages on servers
      ansible.builtin.apt: upgrade=dist force_apt_get=yes
      
- hosts: Ubuntu
  become: true
  become_user: root
  tasks:
    - name: Update apt repo and cache on all Debian/Ubuntu boxes
      ansible.builtin.apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

    - name: Upgrade all packages on servers
      ansible.builtin.apt: upgrade=dist force_apt_get=yes