- hosts: Fedora
  become: true
  tasks:
    - name: Upgrade all dnf packages 
      ansible.builtin.dnf:
        name: "*"
        state: latest

- hosts: OMV
  become: true
  tasks:
    - name: Update apt packages
      ansible.builtin.apt: 
        upgrade: yes
        update_cache: yes
      
- hosts: Ubuntu
  become: true
  tasks:
    - name: Update apt packages
      ansible.builtin.apt: 
        upgrade: yes
        update_cache: yes